### ISSUE TITLE
Create Spawn Zones

### ISSUE THREAD

**Issue by Forthoney** [Forthoney/recurring-nightmare#51]
When the player enters a specific zone/arena, enemies fitting that location should spawn.
It can be something like a triggerable collider (meaning no physical collision) that detects when the player triggers it.
It would then spawn some enemys in specific locations.
We should be able to customize in the editor (i.e. SerializeField)
* list of spawn locations (list of Vector 3 or Vector 2)
* how many enemies to spawn
* how are we choosing where to spawn the enemies. Is it one per location? Is it random? Can multiple enemies spawn one after the other in the same spot?

**The last point should be also discussed with the producers and the design team**

**Comment by nightflowering** [comment]
Added a very basic EnemySpawner class and prefab that just spawns enemies according to a time interval. We need to add a lot more functionality that makes it detect collision with the player, etc.

**Comment by yiwenchen1999** [comment]
Added functionality to detect collision and define types of enemies(now there is only one)+positions in serialized fields. To use, use EnemySpawner as the script on the spawner prefab, to define enemy types, and drag enemies in the enemy prefab list; to add an enemy to the scene, specify the newly added enemy type and position in the corresponding lists. TODO: merge into main branch
