### ISSUE TITLE
Create flying enemy

### ISSUE THREAD

**Issue by Forthoney** [Forthoney/recurring-nightmare#60]
Make an enemy that flies and tracks the player

**Comment by Forthoney** [comment]
Arguably not a very easy thing to implement because the flying enemy would have to pathfind its way to the player

**Comment by JARVISHHH** [comment]
current branch FlyingEnemy

**Comment by JARVISHHH** [comment]
#71 
#72

**Comment by JARVISHHH** [comment]
### How to make NavMesh
#### Easy way
1. Copy and paste the NavMesh object into a scene
2. Make sure the NavMesh object is togged(can be seen), click Bake under its Navigation Surface component.

#### Create from the start (From https://github.com/h8man/NavMeshPlus)
1. Create Empty Object in scene root.
2. Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after.
3. Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
4. (This step had been down under platformer prefab, so we can skip this step. Only do this if we have new scene objects obstacles) Add "Navigation Modifier" component to scene objects obstacles, override the area.
5. In "Navigation Surface" hit Bake.
